# Generated by Django 4.2.1 on 2023-07-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson4', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adversiment',
            new_name='Advertisement',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='descript',
            new_name='description',
        ),
    ]
