# Generated by Django 4.2.1 on 2023-07-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson4', '0002_rename_adversiment_advertisement_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
