# Generated by Django 4.2.1 on 2023-08-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson4', '0005_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='module4/lesson4/static/img/adv.png', upload_to='advertisements/', verbose_name='изображение'),
        ),
    ]
